- hosts: localhost
  connection: local
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: src/ansible/tasks/dotfiles.yaml
    - import_tasks: src/ansible/tasks/install_utilities.yaml
    - import_tasks: src/ansible/tasks/ssh.yaml
    - import_tasks: src/ansible/tasks/zsh.yaml
