- hosts: localhost
  connection: local
  pre_tasks:
    - import_tasks: src/ansible/tasks/pre_tasks.yaml
    - import_tasks: src/ansible/tasks/directories.yaml

  tasks:
    - import_tasks: src/ansible/tasks/zsh.yaml
    - import_tasks: src/ansible/tasks/dotfiles.yaml
    - import_tasks: src/ansible/tasks/tools.yaml
    - import_tasks: src/ansible/tasks/sdkman.yaml
    - import_tasks: src/ansible/tasks/neovim.yaml
    - import_tasks: src/ansible/tasks/java.yaml
    - import_tasks: src/ansible/tasks/js.yaml
    - import_tasks: src/ansible/tasks/bitwarden-cli.yaml
    - import_tasks: src/ansible/tasks/python.yaml