- name: "Install bitwarden CLI (Debian)"
  block:
    - name: "Ensure bitwarden directories exist"
      ansible.builtin.file:
        path: "{{ ansible_facts.env.HOME }}/.local/bin/tools/bitwarden/bin"
        state: directory
        mode: '0755'

    - name: "Download and install Bitwarden CLI"
      ansible.builtin.unarchive:
        src: "https://vault.bitwarden.com/download/?app=cli&platform=linux"
        dest: "{{ ansible_facts.env.HOME }}/.local/bin/tools/bitwarden/bin"
        remote_src: yes
        mode: '0755'
        creates: "{{ ansible_facts.env.HOME }}/.local/bin/tools/bitwarden/bin/bw"
        extra_opts:
          - "-j"  # Extract just the files without directory structure
  when: ansible_facts.os_family == "Debian"
  tags:
    - initial-setup
    - bitwarden

- name: "Install Bitwarden CLI (macOS)"
  community.general.homebrew:
    name: "{{ bitwarden.brew_formulae }}"
    state: present
  when: ansible_facts.os_family == "Darwin"
  tags:
    - initial-setup
    - bitwarden