- name: "Create standard user directories"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - { path: ".ssh", mode: "0700" }
    - { path: "source-code" }
    - { path: ".local/bin/tools" }
  tags:
    - initial-setup
    - directories

- name: "Create apt keyrings directory (Debian)"
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: ansible_facts.os_family == "Debian"
  tags:
    - initial-setup
    - directories