- name: "Create standard user directories"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - { path: ".ssh", mode: "0700" }
    - { path: "source-code" }
    - { path: ".local/bin/tools" }
    - { path: "/etc/apt/keyrings" }
  tags:
    - initial-setup
    - directories