- name: "Install GNU Stow"
  become: true
  package:
    name: stow
    state: present
- name: "Clone dotfiles"
  ansible.builtin.git:
    repo: 'https://github.com/mtkhawaja/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main