# See: https://github.com/cli/cli/blob/trunk/docs/install_linux.md

- name: "Download GitHub GPG key:"
  become: true
  shell: wget -qO - https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/githubcli-archive-keyring.gpg
  tags:
    - initial-setup
    - github

- name: "Configure the GitHub apt repository"
  become: true
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list
  tags:
    - initial-setup
    - github

- name: "Update apt"
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - initial-setup
    - github

- name: "Install GitHub CLI"
  become: true
  package:
    name: "gh"
    state: latest
  tags:
    - github
