---
# Java installation via SDKMAN

- name: "Install Java 21 (LTS) via SDKMAN"
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install java 21-tem
  args:
    executable: /bin/bash
  register: java_install_result
  changed_when: "'is already installed' not in java_install_result.stdout"
  tags:
    - java
    - sdkman

- name: "Install Java development tools via SDKMAN"
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install {{ item }}
  args:
    executable: /bin/bash
  loop:
    - maven
    - gradle
  register: tool_install_result
  changed_when: "'is already installed' not in tool_install_result.stdout"
  tags:
    - java
    - sdkman