# See: https://adoptium.net/installation/linux/
- name: "Download the Eclipse Adoptium GPG key:"
  become: true
  shell: wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor -o /etc/apt/keyrings/adoptium.gpg

- name: "Configure the Eclipse Adoptium apt repository"
  become: true
  shell: echo "deb [signed-by=/etc/apt/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

- name: "Update apt"
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present

- name: "Install Java 8, 17, 21"
  become: true
  package:
    name:
      - "temurin-8-jdk"
      - "temurin-17-jdk"
      - "temurin-21-jdk"