- name: "Download and import the Nodesource GPG key"
  become: true
  shell: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

- name: "Create Nodesource apt repository"
  become: true
  shell: NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && apt update

- name: "Install nodejs and npm"
  become: true
  package:
    name:
      - "nodejs"
    state: present