- name: "Download and import the Node source GPG key"
  become: true
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /tmp/nodesource-repo.gpg.key
    mode: '0644'
  register: gpg_key_downloaded
  tags:
    - initial-setup
    - js

- name: "Import NodeSource GPG key"
  become: true
  ansible.builtin.shell: cat /tmp/nodesource-repo.gpg.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg
  args:
    creates: /etc/apt/keyrings/nodesource.gpg
  when: gpg_key_downloaded is changed
  tags:
    - initial-setup
    - js

- name: "Create Nodesource apt repository"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_24.x nodistro main"
    filename: nodesource
    state: present
    update_cache: true
  tags:
    - initial-setup
    - js

- name: "Install nodejs"
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: false
  tags:
    - initial-setup
    - js

- name: "Clean up temporary files"
  become: true
  ansible.builtin.file:
    path: /tmp/nodesource-repo.gpg.key
    state: absent
  tags:
    - initial-setup
    - js