- name: "Remove neovim"
  shell: rm -rf ~/neovim
  tags:
    - cleanup
    - initial-setup
    - nvim

- name: "Get Packer"
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - initial-setup
    - nvim


- name: "Clone Neovim"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - initial-setup
    - nvim


- name: "Build neovim"
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - initial-setup
    - nvim


- name: "Install neovim"
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - initial-setup
    - nvim


