- name: "Remove neovim source directory if exists (Debian)"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/neovim"
    state: absent
  when: ansible_facts.os_family == "Debian"
  tags:
    - cleanup
    - initial-setup
    - nvim

- name: "Install Neovim (macOS)"
  community.general.homebrew:
    name: "{{ neovim.brew_formulae }}"
    state: present
  when: ansible_facts.os_family == "Darwin"
  tags:
    - initial-setup
    - nvim

- name: "Create Packer plugin directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start"
    state: directory
    mode: '0755'
  tags:
    - initial-setup
    - nvim

- name: "Get Packer"
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    clone: yes
    update: yes
  tags:
    - initial-setup
    - nvim

- name: "Install Neovim build dependencies (Debian)"
  become: true
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - pkg-config
    state: present
  when: ansible_facts.os_family == "Debian"
  tags:
    - initial-setup
    - nvim

- name: "Clone Neovim (Debian)"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ ansible_env.HOME }}/neovim"
    clone: yes
    update: yes
  when: ansible_facts.os_family == "Debian"
  tags:
    - initial-setup
    - nvim

- name: "Build neovim (Debian)"
  ansible.builtin.command:
    cmd: make -j 20
    chdir: "{{ ansible_env.HOME }}/neovim"
  when: ansible_facts.os_family == "Debian"
  tags:
    - initial-setup
    - nvim

- name: "Install neovim (Debian)"
  become: true
  ansible.builtin.command:
    cmd: make install
    chdir: "{{ ansible_env.HOME }}/neovim"
  when: ansible_facts.os_family == "Debian"
  tags:
    - initial-setup
    - nvim