- name: "Update apt"
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  tags:
    - initial-setup

- name: "Install apt-transport-https, ca-certificates and gnupg"
  become: true
  package:
    name:
      - "apt-transport-https"
      - "gnupg"
      - "ca-certificates"
    state: present
  tags:
    - intial-setup

- name: "Install powerline fonts"
  become: true
  package:
    name: fonts-powerline
    state: present
  tags:
    - initial-setup

- name: "Install locales"
  become: true
  package:
    name:
      - "locales"
      - "locales-all"
    state: present
  tags:
    - initial-setup
