- name: "Update apt cache"
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - initial-setup
    - packages

- name: "Install system packages"
  become: true
  ansible.builtin.apt:
    name: "{{ item.packages }}"
    state: present
  loop:
    - { packages: [ "apt-transport-https", "gnupg", "ca-certificates" ], description: "Package management dependencies" }
    - { packages: [ "fonts-powerline" ], description: "Powerline fonts" }
    - { packages: [ "locales", "locales-all" ], description: "Locale support" }
  tags:
    - initial-setup
    - packages