- name: "Install common CLI tools"
  become: true
  ansible.builtin.apt:
    name:
      - "tmux"
      - "jq"
      - "xclip"
      - "tldr"
      - "fzf"
      - "curl"
      - "wget"
      - "htop"
      - "lsof"
      - "unzip"
      - "zip"
      - "gettext"
      - "tofrodos"
      - "neofetch"
      - "rsync"
      - "tree"
      - "expect"
    state: present
    update_cache: true
  tags:
    - initial-setup
    - cli-tools

- name: "Download eza GPG key"
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    dest: /tmp/eza.asc
    mode: '0644'
  register: eza_key_downloaded
  tags:
    - initial-setup
    - cli-tools
    - eza

- name: "Import eza GPG key"
  become: true
  ansible.builtin.shell: cat /tmp/eza.asc | gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  args:
    creates: /etc/apt/keyrings/gierens.gpg
  when: eza_key_downloaded is changed
  tags:
    - initial-setup
    - cli-tools
    - eza

- name: "Add eza repository"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"
    filename: gierens
    state: present
    update_cache: true
  tags:
    - initial-setup
    - cli-tools
    - eza

- name: "Install eza"
  become: true
  ansible.builtin.apt:
    name: eza
    state: present
    update_cache: false
  tags:
    - initial-setup
    - cli-tools
    - eza

- name: "Clean up eza temporary files"
  become: true
  ansible.builtin.file:
    path: /tmp/eza.asc
    state: absent
  tags:
    - initial-setup
    - cli-tools
    - eza

- name: "Install man pages"
  become: true
  ansible.builtin.apt:
    name:
      - "man-db"
      - "manpages-posix"
    state: present
  tags:
    - initial-setup
    - cli-tools

- name: "Install build tools"
  become: true
  ansible.builtin.apt:
    name:
      - "build-essential"
      - "cmake"
      - "pkg-config"
      - "libpthread-stubs0-dev"
      - "lua5.1"
      - "libtool"
      - "libtool-bin"
      - "ninja-build"
    state: present
  tags:
    - initial-setup
    - cli-tools