- name: Install optional Yazi dependencies
  become: true
  apt:
    name:
      - ffmpeg
      - p7zip-full
      - poppler-utils
      - fd-find
      - ripgrep
      - fzf
      - zoxide
      - imagemagick
    state: present
    update_cache: true
  tags:
    - yazi
    - cli-tools

- name: Ensure fd is symlinked as fd (for compatibility)
  become: true
  file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
    force: true
  tags:
    - yazi

- name: Ensure ~/.local/bin exists for Yazi binary
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'
  tags:
    - yazi

- name: Download Yazi latest release binary
  get_url:
    url: "https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-gnu.zip"
    dest: "/tmp/yazi.zip"
    mode: '0644'
  tags:
    - yazi

- name: Unzip Yazi binary to ~/.local/bin
  unarchive:
    src: "/tmp/yazi.zip"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
    extra_opts: [ "-j" ]  # flatten archive structure
  tags:
    - yazi

- name: Make Yazi executable
  file:
    path: "{{ ansible_env.HOME }}/.local/bin/yazi"
    mode: '0755'
    state: file
  tags:
    - yazi

- name: Add .local/bin to PATH in .zshenv if not present
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    create: yes
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
  tags:
    - yazi
